import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {
  RecoilRoot,
} from 'recoil';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <RecoilRoot>
      <html lang="en">
        <body className={inter.className}>
          <div className="min-w-[390px] max-w-[500px]">
            {children}
          </div>
        </body>
      </html>
    </RecoilRoot>
  )
}
